### ISSUE TITLE
.setup menu only displays "1. Start practice mode"

### ISSUE THREAD

**Issue by mfjeldheim** [splewis/csgo-practice-mode#32] opened 2017-06-08 14:42 UTC
### Expected behavior
When typing .setup in chat the menu that pops up normally shows "Start practice mode" followed by different menu options and categories from the practicemode.cfg

### Actual behavior
When typing .setup in the chat menu only "Start practice mode" shows up, when you click 1 for enabling practice mode it says "Practice mode enabled" but you don't get any other menu options. Only thing that shows is "1. Disable Practice mode and 9. Exit", also things like unlimited grenades, ammo, no-clip etc does not work, as if the plugin isn't working even if it is listed in the sm plugins list and the .setup work on the level it does, although with limited options

### Steps to reproduce
- Plugin version: 1.1.2
- Sourcemod version: 1.8
- Server version: v1.35.8.5
- Type .setup
- Menu shows up with no input options

This used to work before the recently released patches, I believe it might have happened after the new operation patch came out, although I can't guarantee that a 100%.

**Comment by splewis** [comment] 2017-06-09 02:51
Can you post what you have in the config file: addons/sourcemod/configs/practicemode.cfg 

And any error logs in the addons/sourcemod/logs directory. Thanks.

**Comment by mfjeldheim** [comment] 2017-06-10 09:06
// This plugin also creates 3 new game cvars you can use when it is loaded:
// - sm_infinite_money (sets player cash to 16000 every second)
// - sm_grenade_trajectory_use_player_color (default 0, sets player grenade
//   trajectories to their cl_color setting)
// - sm_allow_noclip (allows .noclip in chat)
//
// Furthermore, it reimplements the grenade trails sv_grenade_trajectory
// normally creates. These are reimplemented since they are bugged and don't
// show on dedicated servers, so this plugin "patches" that behavior with its
// own grenade trail implementation.

"practice_settings"
{
	"binary_options"
	{
		"required_settings"
		{
			"changeable"		"0"
			"enabled"
			{
				"mp_freezetime"		"1"
				"bot_quota"		"0"
				"mp_autokick"		"0"
				"mp_autoteambalance"		"0"
				"ammo_grenade_limit_total"		"6"
				"mp_death_drop_gun"		"0"
				"mp_death_drop_defuser"		"0"
				"mp_death_drop_grenade"		"0"
				"mp_weapons_allow_typecount"		"25"
				"mp_warmup_end"		""
				"bot_kick"		""
			}
		}
		"cheats"
		{
			"name"		"Cheats"
			"default"		"disabled"
			"enabled"
			{
				"sv_cheats"		"1"
			}
		}
		"respawning"
		{
			"name"		"Respawning"
			"default"		"enabled"
			"enabled"
			{
				"mp_respawn_on_death_ct"		"1"
				"mp_respawn_on_death_t"		"1"
			}
		}
		"infiniteammo"
		{
			"name"		"Infinite ammo"
			"default"		"enabled"
			"enabled"
			{
				"sv_infinite_ammo"		"2"
			}
		}
		"infinitemoney"
		{
			"name"		"Infinite money"
			"default"		"enabled"
			"enabled"
			{
				"sm_infinite_money"		"1"
			}
		}
		"grenadetrajectory"
		{
			"name"		"Show grenade trajectories"
			"default"		"enabled"
			"enabled"
			{
				"sv_grenade_trajectory"		"1"
				"sm_grenade_trajectory_use_player_color"	"1" // set to 0 if you want all grenade trails to be green instead of using each client's cl_color
			}
		}
		"blockroundendings"
		{
			"name"		"Block round endings"
			"default"		"enabled"
			"enabled"
			{
				"mp_ignore_round_win_conditions"		"1"
			}
		}
		"buyanywhere"
		{
			"name"		"Buy anywhere"
			"default"		"enabled"
			"enabled"
			{
				 "mp_buy_anywhere"		"1"
				 "mp_buytime"		"99999999"
			}
		}
		"showimpacts"
		{
			"name"		"Show bullet impacts"
			"default"		"enabled"
			"enabled"
			{
				"sv_showimpacts"		"1"
			}
		}
		"noclip"
		{
			"name"		"Allow noclip"
			"default"		"enabled"
			"enabled"
			{
				"sm_allow_noclip"		"1"
			}
		}
		"solidteammates"
		{
			"name"		"Solid teammates"
			"default"		"enabled"
			"enabled"
			{
				"mp_solid_teammates"		"1"
			}
		}
		"allradar"
		{
			"name"		"Show all players on radar"
			"default"		"enabled"
			"enabled"
			{
				"mp_radar_showall"		"1"
			}
		}
	}
}


This is what I got in my "practicemode.cfg" 
I wasn't able to find anything within the "sourcemod/logs" directory except a file called "mpuk-fake"

**Comment by bykidi** [comment] 2017-06-10 10:32
type 'sm pluguns' in the console as an admin and see for practicemode plugin

**Comment by mfjeldheim** [comment] 2017-06-10 10:34
Funny thing is that it shows up but it still doesn't work as expected regarding the .setup menu. Many of the options are not shown;

**Comment by bykidi** [comment] 2017-06-10 10:36
how fresh is your sourcemod+metamod installations?

**Comment by mfjeldheim** [comment] 2017-06-10 10:38
Pretty fresh, I re-installed the server a couple of weeks ago (say 5-6) and it worked recently but it hasn't been working since the Operation update they had as far as I know. Perhaps I could reinstall them both again if that is the issue. Sounds weird though

**Comment by splewis** [comment] 2017-06-10 16:07
> Funny thing is that it shows up but it still doesn't work as expected regarding the .setup menu. Many of the options are not shown; 16 "CS:GO PracticeMode" (1.1.2) by splewis

It sounds pretty clear that the plugin can't read your settings file.

I can't reproduce your problems; I use practicemode on a daily basis and have no issues.

**Comment by mfjeldheim** [comment] 2017-06-10 16:09
Alrighty, that actually helps alot knowing that it works for you. I'll try to reinstall the server and install all the plugins and mods again. Thanks man!

**Comment by splewis** [comment] 2017-07-08 02:42
I'm going to close this since there's been no update and i don't think there is a bug here. Feel free to reopen if you think something is broken still.

**Closed by splewis** 2017-07-08 02:42 UTC
