### ISSUE TITLE
Access to .prac to everyone.

### ISSUE THREAD

**Issue by wayLANder3** [splewis/csgo-practice-mode#50] opened 2017-09-20 13:14 UTC
I can't give access for .prac to all players (delete flag "g" for access".
I added in overrides:
```
Overrides
{
 "sm_prac" ""
}
```
But i don't have access for this mode (i restarted server after editing overrides ofc)

- Plugin version: 1.1.3
- Sourcemod version: 1.8.0.6027

**Comment by splewis** [comment] 2017-09-21 01:22
.prac isn't a command on the version you're using.

Use ``.setup``.

**Comment by wayLANder3** [comment] 2017-09-21 09:36
Sorry, i will update to the latest version 1.2.0
And give feedback

**Comment by wayLANder3** [comment] 2017-09-22 00:10
Ok, i can't solve this without editing .sp

  RegConsoleCmd("sm_prac", Command_LaunchPracticeMode, "Launches practice mode");
  RegConsoleCmd("sm_launchpractice", Command_LaunchPracticeMode,
              "Launches practice mode");
  RegConsoleCmd("sm_practice", Command_LaunchPracticeMode,
              "Launches practice mode");

  RegAdminCmd("sm_exitpractice", Command_ExitPracticeMode, ADMFLAG_CHANGEMAP,
              "Exits practice mode");
  RegAdminCmd("sm_translategrenades", Command_TranslateGrenades, ADMFLAG_CHANGEMAP,
              "Translates all grenades on this map");
  RegAdminCmd("sm_fixgrenades", Command_FixGrenades, ADMFLAG_CHANGEMAP,
              "Reset grenade ids so they are consecutive and start at 1.");

This works now.

**Comment by splewis** [comment] 2017-09-22 06:23
I can't reproduce this by setting admins_override.cfg to
```
Overrides
{
	"sm_prac"		""
}
```

I don't think your changes to the configs/admins_override.cfg were saved.

**Comment by splewis** [comment] 2017-09-29 01:19
I'm closing since I haven't been able to reproduce any issues.

**Closed by splewis** 2017-09-29 01:19 UTC
